### PR TITLE
fix: add aria label to map

### LINKED ISSUE #528: Mac OS Voiceover in Safari says Visualization is Empty
**Actual Behavior:**

When focus goes to the visualization map the screen reader Voiceover in Safari says that "You are currently in a empty visualization" 

When I...

Focus on the map while using Voiceover.

1. go to https://cms-staging.andrew.cmu.edu/covid/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20200701&signalType=value&encoding=color&mode=overview
2. Activate Voiceover (if not already activated)
3. Tab to map in page

**Expected behavior**

The screenreader should be able to read the current state of the map (eg options selected)

**Screenshots**

image

**Rating Scale (1 is minor, 7 is severe):**

5 

**Context**

- Browser: Safari Mac OS

### PR DESCRIPTION
**Pull request by sgratzl**
closes #528

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

add an aria description to the map visualization and a proper role. To test just follow the issue but you will hear a different description

### CODE REVIEW

**Review by tildechris — APPROVED** [review]
Code LGTM.  Will need somebody with MacOS to verify. (Is there another way?)

**Comment by tildechris** [comment]
@cgg-cmu can you verify that https://deploy-preview-541--cmu-delphi-covidcast.netlify.app works as expected?

**Comment by dlaliberte** [comment]
> @cgg-cmu can you verify that https://deploy-preview-541--cmu-delphi-covidcast.netlify.app works as expected?

It works for me.

**Comment by cgg-cmu** [comment]
> > @cgg-cmu can you verify that https://deploy-preview-541--cmu-delphi-covidcast.netlify.app works as expected?
> 
> It works for me.

Looks good to me as well!

**Comment by tildechris** [comment]
LGTM, merging.

**Pull request merged**
