### PR TITLE
add week signal support

### PR DESCRIPTION
**Pull request by sgratzl**
**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

add support for weekly signals in the dashboard builder, export data, indicator status, and general covidcast 2.0

image

working
 * dashboard
 * indicator status
 * export
 * covidcast (with the patch below) - mostly

for the normal covidcast one hack is to add this to the generated.json:

```
{
    "name": "NHCS Mortality",
    "id": "nchs-mortality",
    "signal": "deaths_allcause_incidence_prop",
    "rawSignal": null,
    "type": "late",
    "levels": ["state"],
    "xAxis": "Week",
    "yAxis": "per 100,000 people",
    "format": "per100k",
    "unit": "per 100,000 people",
    "highValuesAre": "bad",
    "is7DayAverage": true,
    "isWeeklySignal": true,
    "hasStdErr": false,
    "highlight": [],
    "mapTitleText": "TODO",
    "description": "TODO",
    "credits": "TODO",
    "links": [
      "<a href=\"https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/hospital-admissions.html\">Technical description</a>"
    ]
  },
```

### CODE REVIEW

**Comment by krivard** [comment]
[Percentage of Expected Deaths shows on the choropleth and table, but not on the time series](https://deploy-preview-995--cmu-delphi-covidcast.netlify.app/dashboard/?utm_source=github&utm_campaign=bot_dp&date=20210711&sensor=nchs-mortality-deaths_percent_of_expected#N4Ig9gTgJgphIC4DaIC2BDADgfQEwgBoQIYBzASzADsAXdAIwBsZsBmQkR8qlgVhAC6RAM50aMYYlBce2fglAB3clBoALRLyJqY5UmpqJcRAF5wwiGhACuMIhHSLEAM3SNhdkAGNrqa43QacgA3GBc3DwBfezJKWgZmNikQZVUNBGMQHT0DRFYRSBoAYQhycVL0RBAqdFQwgohi0vLydAARCS9LGxhotCw8ZNT1PO1dfUMEVki+r2pnPUkFfpx8ZeZQxirRQLC+mT5koLqAMQc67ZgqYUgQGcigA):

image

there are some other problems with the meta data on that signal, i'm going to fix them and pull a fresh copy into epidata

**Comment by sgratzl** [comment]
re time series: 
it cannot since this signal doesn't support the nation geo level. The other ones are showing states which are supported

**Review by krivard — COMMENTED** [review]
oh geez right, sorry. for my own reference, that's https://github.com/cmu-delphi/covidcast-indicators/issues/1041 which we hope to fix soon.

NCHS also doesn't go below state level, which makes the county coverage stuff in indicator-status a bit confusing. Any ideas for how to address that?

**Comment by sgratzl** [comment]
> NCHS also doesn't go below state level, which makes the county coverage stuff in indicator-status a bit confusing. Any ideas for how to address that?

not for the overview table, since one row with a different level would be difficult. However, I clarified it in the error message and in the source details it will show a state coverage map.

**Review by krivard — APPROVED** [review]
That works! Thanks 🎉

**Pull request merged**
