### PR TITLE
Add simple expandable line chart

### LINKED ISSUE #897: Expanded timescale timeseries view
Request from @RoniRos: 

> It would be great if it were possible to see a time series from the beginning of the pandemic till now.

**User story**

* As a data power user, 
* I want to see a time series with expandable or expanded x-axis limits, 
* so that I can answer simple research questions about how an indicator has progressed over the full course of the pandemic, without having to write my own custom code

**Additional context**

One way to do this would be to bring up an overlay which full-screens the timeseries, a la the classic map. 
* Is it easy to lift that code?
* How do we wanna activate this view -- click the timeseries? add an icon/link?
* Should this work on mobile (using landscape probably), or just desktop?

Some other approaches, though these all seem more complicated:
* let the user expand backwards/forwards in time directly from the main time series display
* let the user set a global viewing start date or time range in addition to setting the selected date

### PR DESCRIPTION
**Pull request by sgratzl**
closes #897 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

adds a new "Show All Dates" button

image

image

### CODE REVIEW

**Comment by krivard** [comment]
Did this branch off of an irregular part of the repo? looks like it's not picking up the "Published" column in the data anomalies sheet

**Comment by sgratzl** [comment]
> Did this branch off of an irregular part of the repo? looks like it's not picking up the "Published" column in the data anomalies sheet

deploy previews + dev branch is showing all annotations regarding of the published state, see https://github.com/cmu-delphi/www-covidcast/blob/dev/netlify.toml

**Comment by krivard** [comment]
Wacky alignment:
image
image

I either expected symmetrical expansion, fit to window width, or a widget that scrolls within the established page margins a la

**Comment by krivard** [comment]
(oh weird, yours didn't do that. I'm on Chrome 89.0.4389.90, macOS 10.14.6)

**Comment by sgratzl** [comment]
> (oh weird, yours didn't do that. I'm on Chrome 89.0.4389.90, macOS 10.14.6)

can you try again, please. I changed the style and it works for me in Firefox, Chrome and with Browserstack also on Chrome and Safari on MacOS

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
