### PR TITLE
extended scale for covid cases plots

### LINKED ISSUE #1131: Extend limits of color scale
(This should be the last item under v3.1!)

I think we're going to need to extend the limits of the color scale for the beehive & choropleth maps. Looking at cases right now, everything is dark red for the beehive map. Choropleth map is getting saturated in most of the south and southeast as well.

Screen Shot 2022-01-12 at 8 58 05 AM
Screen Shot 2022-01-12 at 8 58 16 AM
 
Can we just add a color to the end of the scale to keep the visualization consistent with what we have for everything below the max value on the color scale? That way the new color would only help distinguish the values about the max. For example, dark purple.

Also while I'm here, can I ask for a reminder of how these scales are computed. Is it manual or data-driven? It appears to be different for state resolution vs county resolution, for the same indicator. But just to double check: it is constant across all views over time and locations, right? Say, as I scroll back arbitrarily far into the past, or zoom into a particular location, the color scale would remain the same?

### PR DESCRIPTION
**Pull request by sgratzl**
closes #1131 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

see issue

please try it out, Currently it will only be done for covid-cases signal not for others.

### CODE REVIEW

**Comment by ryantibs** [comment]
Thank you Sam!  To me this looks like a nice improvement and I like it.

I wonder whether I'm biased by the fact I've already familiarized myself with the color scale, having looked at many of these plots at this point over on the issue #1131. 

Before merging we may want get at least one more unbiased set of eyes to weigh in.  

@capnrefsmmat @krivard @RoniRos Can one of you quick look and see what you think of the extended color scale for cases?  [Click here for convenience](https://deploy-preview-1132--cmu-delphi-covidcast.netlify.app).

For example, is it confusing that light purple is "worse" than dark red?

When we get approval from at least one of these folks, then we can merge this and we should be ready to launch v3.1 !!

**Comment by capnrefsmmat** [comment]
> For example, is it confusing that light purple is "worse" than dark red?

I think so, yes. I like the NYTimes scale because it's perceptually uniform, getting darker as it gets worse:

Screen Shot 2022-01-13 at 2 38 30 PM

When it goes past red, it goes into a dark reddish purple. In the preview for this PR, the purple is more of a nice lavender that's more blue than red, and is much lighter than the lower case values.

I think if you took this scale, removed the lavender part of it, and made the darker purples a bit more red, it'd look good.

**Comment by RoniRos** [comment]
+1 Alex & Ryan (light purple > dark red is a problem.  NYT-like scale is good.)

**Comment by ryantibs** [comment]
Thanks Alex. @sgratzl Can you try what Alex suggests?

**Comment by krivard** [comment]
We should also be careful about contrast -- for example, in this screenshot OH, TX, and AK won't be legible for some users:

image

**Comment by ryantibs** [comment]
I can try to pick specific colors at specific points, but can we try something easier first?

Can we define the extended color scale by just two colors its two ends, medium purple and dark purple.

(Whereas now you start at light purple.)

For medium purple you could use something similar to 2220 on the color scale in Katie's screenshot above, i.e., around the color of Kansas (KS).

For dark purple, the current end of the color scale, i.e., the color of Florida (FL). 

We can see how that looks----there might not be enough diversity in the gradient between those two end colors, but we can try.

**Comment by sgratzl** [comment]
with

#7c187d to #4d014a

image
image

**Review by krivard — APPROVED** [review]
That looks amazing 🔥

**Comment by ryantibs** [comment]
I think it looks good, it has the disadvantage that there's not as much diversity in the "extended range" so it's hard to tell those colors apart, but I think this is about as good as we can get right now, and we should move on.

Thanks for all the iteration Sam.

**Review by ryantibs — APPROVED** [review]

**Comment by ryantibs** [comment]
@sgratzl @krivard This wraps up v3.1. So once this is merged, we should make a release.

**Pull request merged**
