### PR TITLE
small style fixes

### PR DESCRIPTION
**Pull request by sgratzl**
based on #833 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

image

flat survey list and some hr lines

better map switch:
image

### CODE REVIEW

**Comment by tildechris** [comment]
This looks great, but there seems to be some wonkiness with the anchors to the survey results.  The first three worked, but then the others didn't go to the appropriate section

zxvn7r7fia

**Comment by sgratzl** [comment]
not that easy to fix. I tried it now but since after the data has loaded the layout is shifting it might not always work as expected

**Comment by tildechris** [comment]
To capture the discussion: lets link all of the survey sections together with one link if it's hard anchoring on dynamic data.

**Comment by sgratzl** [comment]
> To capture the discussion: lets link all of the survey sections together with one link if it's hard anchoring on dynamic data.

done

**Comment by tildechris** [comment]
It looks like the anchors are still there, and clicking on testing still takes you to the bottom of the page.  Can we change it to be one `a` tag?

The U.S. Pandemic Survey offers insights into public sentiment on: [Symptoms, Mask Use, Vaccines, Social Distancing, Mental Health and Testing](https://deploy-preview-837--cmu-delphi-covidcast.netlify.app/survey-results/?date=20210316)

**Comment by sgratzl** [comment]
> It looks like the anchors are still there, and clicking on testing still takes you to the bottom of the page. Can we change it to be one `a` tag?
> 
> The U.S. Pandemic Survey offers insights into public sentiment on: [Symptoms, Mask Use, Vaccines, Social Distancing, Mental Health and Testing](https://deploy-preview-837--cmu-delphi-covidcast.netlify.app/survey-results/?date=20210316)

done

image

**Review by tildechris — APPROVED** [review]
LGTM.

**Pull request merged**
