### PR TITLE
Tune navigation hints

### LINKED ISSUE #1091: Improve visibility of subpage menu
Currently the only way to get the other dashboard subpages: "Explore an Indicator", "Indicator Status Overview", etc, is to click on the small box in the top right.  This is what is looks like on the dev site for me: 

Screen Shot 2021-12-08 at 8 53 56 PM

Would it look different when it gets launched?  I want to make sure we have a way of drawing visibility to this submenu.  Otherwise a person might think that "Explore a Location" (which is the landing page for the dashboard) may be the only page they get.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #1091 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

image

image

image

what about this for better highlighting navigation options? @ryantibs

### CODE REVIEW

**Comment by ryantibs** [comment]
Some aspects of this are nice but I find it a bit confusing because I don't think there's any way to get back to "Explore a Region" mode once you're in "Explore an Indicator" mode.  If I'm looking at a particular indicator and I click on a region then it takes me to the explore-an-indicator page for that region, not the explore-a-region page for that region.

So I think I would prefer to see some kind of explicit menu to allow the user to toggle between "Explore a Region" and "Explore an Indicator".

**Comment by sgratzl** [comment]
ok, I added the navigation hints you mentioned in the issue:

image

**Comment by ryantibs** [comment]
@sgratzl Looks good.  I'd like to replace "show details" with "explore further" (at the end of the sentences "Click on and region name..." and "Click on an indicator name...").  But then I'm ready to approve.

**Comment by sgratzl** [comment]
done:
image

**Comment by ryantibs** [comment]
Looking good!  

But I still see one more above the beehive/choropleth map: "Click on a state to show this region" --> should be "Click on a state to explore further".

**Review by ryantibs — APPROVED** [review]

**Pull request merged**
