### PR TITLE
feat: rename pages

### PR DESCRIPTION
**Pull request by sgratzl**
**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

changes the title of the pages according to the new "explore" scheme, see also counterpart in www-main soon

### CODE REVIEW

**Comment by tildechris** [comment]
Nav looks good.  I think we need to decide on "INDICATOR: {Indicator Name}" vs. "Explore an INDICATOR", i.e. what the H1 title should be on both the location and indicator pages.

**Comment by sgratzl** [comment]
image

**Comment by sgratzl** [comment]
image

**Review by tildechris — APPROVED** [review]
LGTM.

**Pull request merged**
