### PR TITLE
hospital admission county override

### LINKED ISSUE #1139: CPR hospital admissions for counties only
We will soon have county-level hospital admissions signals in the API from CPR = community profile report.  

While this is technically supposed to be coming from the same data source as that underlying the HHS hospital admissions signals (I've checked this with CDC), for unknown reasons, there are disagreements at this point between the data published by these two sources.  This discrepancy, I'm told by CDC, should be resolvable though, and they're working on that.

Also, it should be noted that by my calculations the CPR signals will be 1 day more latent compared to the HHS signals (available at a 3-day lag, rather than a 2-day lag).

I would like the COVIDcast dashboard to show the CPR signal values for county-level hospital admissions, but still HHS for state-level and national hospital admissions.  This should be seamless and not require the user to change indicators, it would be under the "COVID Hospital Admissions" indicator.  But the data description should indicate clearly that it's actually coming from two different sources, and should warn that---at the moment---there is a discrepancy (sum of county counts do not add up to state counts) for unknown reasons, and we're working with the data stakeholders to fix that.

I believe this should affect the following: 

- When in "indicator mode" with indicator = hospitalizations, region = national, the choropleth map (as a toggle option way from beehive grid) should show CPR county-level signal
- When in "indicator mode" with indicator = hospitalizations, region = any given state or county, the choropleth map should show CPR county-level signal
- When in "indicator mode" with indicator = hospitalizations, region = any given state or county, the data table at the bottom should show CPR county-level signals
- When in "indicator mode" with indicator = hospitalizations, region = any given county, the time series graph should show CPR county-level signals

@sgratzl @RoniRos @krivard Any concerns with this plan?

### PR DESCRIPTION
**Pull request by sgratzl**
closes #1139

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

option to override a signal with another one in the config for a specific geo level. The override is then patched in in both fetching the data and fetching the trend. 

what is missing is adapting the text to notify the user about it at https://docs.google.com/document/d/1llv6xh8jMlmVv7WpyDSv4VgUpFAZQ6QjFUeRxxOinmk/edit#

### CODE REVIEW

**Comment by ryantibs** [comment]
Thanks for the fast turnaround. Unfortunately some things don't seem to work for me:

- topline numbers for counties still say N/A for hospitalizations

- choropleth map not showing anything for dates where it looks like we have data. Note now that we have county data, should be showing choropleth over counties not states (like all other signals---states was a special thing for HHS hospitalizations, before we had counties)

- time series map showing very weird pattern of availability at the county level

Screen Shot 2022-02-27 at 8 55 12 PM
Screen Shot 2022-02-27 at 8 55 43 PM
Screen Shot 2022-02-27 at 8 56 10 PM
Screen Shot 2022-02-27 at 8 56 42 PM

**Comment by ryantibs** [comment]
@dshemetov @korlaxxalrok When the interpolation fix for the county-level hospitalization signal is live, can one of you check the preview ("Browse the preview") to see that it's gone through as expected? (I checked just now and it hasn't yet.)

Once that's done, you could ping @sgratzl and I to confirm on this, and then I could look once more before we merge. 

cc @duanecmu to help track.

**Comment by dshemetov** [comment]
@ryantibs county-level interpolation is [live and looks good](https://delphi.cmu.edu/covidcast/dashboard/?sensor=dsew-cpr-confirmed_admissions_covid_1d_7dav&region=42003#N4Ig9gTgJgphIC4DaIA2BLAdjA+gVhAF0AaEAZwBcBDCmMxUDbfBkAd3SgoAtE9TuMdAHNuFRACZSALzhhEFCAFcYpCFTaIAZlVRkYAXwOkAxmExaR9BIyy4CNkBXQBbGADF1bxORiYykCBGBkA).

**Comment by ryantibs** [comment]
Thanks! I played around with the main dashboard a bit and it looks good to me there as well.

@dshemetov @duanecmu @korlaxxalrok Can one of you play around with this between county, state, and national levels on the main dashboard as well to see that it all works are you expect?

Also, can you confirm: the earliest we have the county-level hospitalization data (from CPR) for is Dec 2020 or so? Because we have state and national hospitalization data (from HHS) going back earlier. See screenshot: 

Screen Shot 2022-05-03 at 5 16 50 PM

**Comment by krivard** [comment]
> Also, can you confirm: the earliest we have the county-level hospitalization data (from CPR) for is Dec 2020 or so?

Correct -- the earliest Community Profile Report is dated 2020-12-17 and contains hospital admissions for the 7-day period ending 2020-12-16. [source page on healthdata.gov](https://healthdata.gov/Health/COVID-19-Community-Profile-Report/gqxm-d9w9); [direct download link](https://healthdata.gov/api/views/gqxm-d9w9/files/4de459d6-23d0-4691-8dd8-f2132ecebf47?download=true&filename=Community_Profile_Report%2020201217_Public.xlsx)

**Comment by ryantibs** [comment]
Also I realized that we don't describe (in the gray box data description box) the fact that at the county level, we're showing data from CPR. I believe it still says it's from HHS. We should fix this. 

@krivard Can you please fix and/or delegate? Thank you!

Then, once fixed, and I hear back that at least one other person played with this staging dashboard, then I'm fine to merge (Katie you can approve yourself---it looks like it's on auto merge as soon as it's approved, so I won't approve yet).

**Comment by krivard** [comment]
> Also, can you confirm: the earliest we have the county-level hospitalization data (from CPR) for is Dec 2020 or so?

The earliest Community Profile Report is dated 2020-12-17, but it does not include county-level hospital admissions. The first CPR including county-level hospital admissions is dated 2021-01-08, and includes the admissions count for the 7-day period ending 2021-01-07.

I checked all geo levels and it looks good:
* Timeseries plots and maps are both working at county, state, and national level.
* Timeseries plots at county level correctly include state and national figures for context
* Maps at state level correctly show county choropleth -- though keep in mind CPR availability lags HHS figures by a few days, so the more recent days have state data but no county data. Currently (on May 6) the most recent day with both state and county figures is May 1, and the most recent day with state figures only is May 4.

**Comment by ryantibs** [comment]
(Great---thank you! So I think just the description is left.)

**Review by ryantibs — APPROVED** [review]

**Comment by sgratzl** [comment]
@krivard I'm not sure what the current status of this PR is

**Comment by duanecmu** [comment]
Just wanted to check to see if there were any status updates for this PR. Thanks!

**Comment by krivard** [comment]
@duanecmu you should be able to see the status updates:
image

This PR has been merged and will be deployed at the next release of www-covidcast. Would you like to [do the honors?](https://github.com/cmu-delphi/www-covidcast#release-process)

**Comment by duanecmu** [comment]
Sure thing. I'll start the deployment today if that's OK.

**Pull request merged**
