### PR TITLE
TEST - Use the qa2 API backend for epidata v4 project testing

### PR DESCRIPTION
**Pull request by korlaxxalrok**
**Prerequisites**:

- [ ] Unless it is a hotfix it should be merged against the `dev` branch
- [ ] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [ ] Build is successful
- [ ] Code is cleaned up and formatted

### CODE REVIEW

**Comment by korlaxxalrok** [comment]
@krivard @sgratzl Sorry, I thought I had already called this out but I did not actually post the comment.

This preview is not working, but after looking at it a bit more it is probably something with the intermediate proxy server, so I need to look a bit more there.

**Comment by korlaxxalrok** [comment]
@krivard Ah, looks like the immediate issue was having missing metadata in qa. Faking with prod data and the preview bits at least render.

**Comment by sgratzl** [comment]
when I run it locally it shows:

image

and also the same picture when I'm using the netlify preview link:

image

**Comment by korlaxxalrok** [comment]
Thanks for taking a look @sgratzl 👍

**Pull request closed without merging**
