### PR TITLE
lab chart experiments

### PR DESCRIPTION
**Pull request by sgratzl**
### Summary

current state of the vega experiments for showing maps and simplified line charts

image (1)
image (2)

### CODE REVIEW

**Comment by sgratzl** [comment]
another experiment: line chart + linked map:


image

**Comment by tildechris** [comment]
I like this draft.  Can we give some affordance to changing the data via touch?  E.g. if I tap and hold can we show the user which date they are selecting and when released it changes the date?

**Comment by sgratzl** [comment]
> I like this draft. Can we give some affordance to changing the data via touch? E.g. if I tap and hold can we show the user which date they are selecting and when released it changes the date?

difficult but possible:

image

see also https://github.com/vega/vega/issues/3065

**Comment by sgratzl** [comment]
another experiment: 

image

**Comment by sgratzl** [comment]
another 
image

**Comment by sgratzl** [comment]
merged the #741 into it:

image

image

image

TODO:
 * how are trends computed/defined
 * how to compute record high/low peak 7-day period without loading all data and check manually
 * we don't have a vaccine signal

**Comment by sgratzl** [comment]
another one:

image

**Comment by sgratzl** [comment]
geo table:

image

**Comment by sgratzl** [comment]
mask vs cases: 

image

**Comment by sgratzl** [comment]
Thermalplot:

image

**Comment by sgratzl** [comment]
current mobile state:

image

image

image

image

image

**Pull request merged**
