### PR TITLE
Change summary charts to hospital admissions

### LINKED ISSUE #1195: Add flu signals to dashboard
Signals to add:
* HHS influenza admissions
* CHNG outpatient flu

### PR DESCRIPTION
**Pull request by krivard**
closes #1195 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

* Swaps out cases sensor for hospital admissions sensor on summary page in map and plot sections.
* Also renames overview panel from "cases overview" since we are likely to eventually phase out cases.

### CODE REVIEW

**Comment by krivard** [comment]
Failed checks are spurious (a netlify config problem not a this-PR problem; it's now fixed on the netlify end but I can't seem to convince github to try the checks again)

**Comment by christymelucci** [comment]
I see that the intended changes have been successfully, but also see three minor unexpected items that I will note here just in case they are of interest. To review these items, see text comments on the attached screenshot.

[2022-12-08.pdf](https://github.com/cmu-delphi/www-covidcast/files/10190521/2022-12-08.pdf)

**Comment by krivard** [comment]
Great attention to detail! However, these all appear on the currently live version as well, so were not introduced in this PR. I've made new bugs for them in most cases:
* Expander not on Beehive Grid view -- I suspect this is on purpose; the expander is definitely needed in Choropleth mode because counties are quite small, but the beehive cells are probably chunky enough not to need a zoomed-in view. If you find the beehive cells to be too small though, I can create an issue for this (or you can, either way) -- let me know
* #1202 
* #1203

**Review by nolangormley — APPROVED** [review]
LGTM!

Found a bug with firefox when you open the inspect window. This bug was not introduced in this PR though so it's not fully relevant.

**Pull request merged**
