### PR TITLE
show data anomaly annotations

### LINKED ISSUE #601: Consider supporting an explainer popup to provide additional details on exceptional phenomena
All of humanity's technology systems are learning how to handle a global pandemic at the same time, and we should expect a commensurate number of errors and weird edge cases. If we could provide users with greater context for interpreting these scenarios, it would both increase trust in our tool and help elevate the public's understanding of the scientific process.

**User story**

The health department of Wyoming has been including probable (but untested) cases in their case count for months. When they decide to switch to only including tested confirmed cases, the apparent case incidence plummets to huge negative numbers. This shows up in the map as Wyoming being a sole buttercup in a field of dark red. A visual cue lets the user know that yes, this is the correct display, and it is indeed weird. When clicked, it brings up a card that explains the additional context, and links to the relevant announcement on the Wyoming DoH website.

Screenshot lifted from @tildechris's outages report:

image

**Additional context:**

In addition to the bulk updates and negative incidence events that happen from time to time, this feature could also be used to explain things like:
* Why some counties are grouped together (they share public health resources and don't report separately)
* Why the daily count in NYC counties is sometimes fractional

### PR DESCRIPTION
**Pull request by sgratzl**
closes #601 

current state: 
image

sub tasks
 * [ ] define api -> which URL should be used?
 * [x] load annotations
 * [x] design annotations
 * [x] add annotations to history line chart
 * [x] add annotations to general indicator overview
 * [x] add annotations to tables?
 * [ ] add annotations to maps?

### CODE REVIEW

**Comment by sgratzl** [comment]
history line annotations:

image

**Comment by Letsgohyde** [comment]
This is looking great, few design changes: 

1. Can we reorder the alert header copy: Icon, "Low spiky values" [date range]
2. Increase contrast: Darker shade of orange for the text and icon. #D46B08

Thanks @sgratzl

**Comment by sgratzl** [comment]
tables:

image

image

**Review by tildechris — APPROVED** [review]
LGTM! Great job, this is a surprisingly concise change.

**Pull request merged**
