### PR TITLE
additional export infos

### LINKED ISSUE #599: Document the meanings of columns in the exported CSV files
It would be great if somewhere in the Export Data interface, perhaps when you click the CSV button, it would provide a summary of the column names and what they mean.

**User story**

A non-technical user decides to download our data to make a spreadsheet or graph. They press the CSV button and get a file with columns like "geo_value", "time_value", "value", "lag", etc., and don't know what these mean.

**Additional context**

We have documentation in several places that could be used here:

* [API docs](https://cmu-delphi.github.io/delphi-epidata/api/covidcast.html#response)
* [R package return value docs](https://cmu-delphi.github.io/covidcast/covidcastR/reference/covidcast_signal.html#value)
* [Python package return value docs](https://cmu-delphi.github.io/covidcast/covidcast-py/html/signals.html#covidcast.signal)

### PR DESCRIPTION
**Pull request by sgratzl**
closes #599 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

extends the exports page, by

 * showing the common help icon next to signals
 * add more links to meaning of data structures
 * add a CSV version with links and hints how to use it with wget

image

@capnrefsmmat what do you think?

(note the changehc signal is just part of my system)

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Question: Most of our data is released under the terms of the CC-BY license, but some data sources have other terms. Is there a good way for us to embed licensing information and show it on the download page?

I think the "We would be happy for you..." would just need to be conditional on source, so by default it would say "under the terms of the Creative Commons Attribution license", but for other sources it would say the data is provided by [some source] under [some terms].

**Comment by sgratzl** [comment]
> I think the "We would be happy for you..." would just need to be conditional on source, so by default it would say "under the terms of the Creative Commons Attribution license", but for other sources it would say the data is provided by [some source] under [some terms].

what about adding a field to the signal description at https://docs.google.com/document/d/1RLy4O-gtACVjLEVD_vxyPqvp9nWVhqEjoWAKi68RKpg/edit#heading=h.oxebzdy7nl8w which can cover those cases?

**Comment by sgratzl** [comment]
current state: 

* renamed Data source to "Cases and Deaths"
* add see also with the links from the description
* incorporate the credit section from the description field in google doc

image

**Comment by tildechris** [comment]
Do we expect the wget command to work on the existing version?

```
wget --content-disposition "https://delphi.cmu.edu/csv?signal=doctor-visits:smoothed_adj_cli&start_day=2020-10-24&end_day=2020-11-24&geo_type=county"
```

Failed for me with a `502: Bad Gateway`.

**Comment by sgratzl** [comment]
> Failed for me with a `502: Bad Gateway`.

seems more like the server is down

**Review by tildechris — APPROVED** [review]
LGTM.  Thanks Sam.

**Comment by tildechris** [comment]
Merging in order to make release branch

**Pull request merged**
