### PR TITLE
style: change survey parameter style

### LINKED ISSUE #716: Survey dashboard: v2 styling for location and date pickers
Hey Sam, here's the updated design based on the feedback: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=1720%3A47

1. Remove breadcrumbs from COVIDcast only
2. New styling for location picker
3. New styling for datepicker / move cal icon to prepend the [date]
4. Rename "Outline" to "Survey questions"

Thanks, let me know if there's anything I can clarify :)

### PR DESCRIPTION
**Pull request by sgratzl**
closes #716 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

current state:

image

@Letsgohyde take a look, please

### CODE REVIEW

**Comment by tildechris** [comment]
Can you make the spacing below the geo search bar match the spacing above?

image

Also, what are your thoughts on selecting all text in the search box when it is focused?  I when I go to type in a different geo I found myself typing in the middle of the previous value.  I think select-all-on-focus is default behavior in many search boxes.

**Comment by sgratzl** [comment]
selectonclick

**Comment by tildechris** [comment]
Thanks the spacing and highlighting looks good.  For counties without enough data, the "no data available" is above the search bar (z-index issue maybe?):

image

**Comment by sgratzl** [comment]
> Thanks the spacing and highlighting looks good. For counties without enough data, the "no data available" is above the search bar (z-index issue maybe?):

fixed

**Comment by Letsgohyde** [comment]
This is looking great, can you update the spacing between the cal arrows to 36px? 

image

Thanks @sgratzl

**Comment by Letsgohyde** [comment]
Aside from that: LGTM :)

**Comment by Letsgohyde** [comment]
Other styling and spacing feedback: 
1. 
image
2. 
image
3. 
image
4. 
image

Thanks @sgratzl

**Comment by sgratzl** [comment]
image

it is difficult to create a pixel-perfect match of the design cause
 * the search field has to be compatible with the remaining website, since it is the same widget as in the other views
 * the HTML/DOM hierarchy implied by the implementation makes it tricky to sometimes align items
 * it should work on different screen resolutions

we can take a look at it together in a screenshare session, since in my experience it is faster than applying designs based on screenshots

**Review by tildechris — APPROVED** [review]
LGTM.  I think this version looks and functions well.  Thanks.

**Comment by Letsgohyde** [comment]
Thanks for making those updates and sharing the limitations. LGTM!  :)

**Pull request merged**
