### PR TITLE
Encode visible indicator in hash

### LINKED ISSUE #892: Permit deep linking into Indicator Status:Single Indicator view
It would be great if I could send someone a link directly to the "Single Indicator" view of the Indicator Status interface. 

**User story**

Currently you can only link people to the overview page. If someone asks me about the coverage or typical lag for one of our data sources, I have to link them to the overview and tell them what to click next. With a direct link, they could get their question answered with a single click.

**Additional context**

This is what currently shows up in the address bar when you're on the Single Indicator view:
* https://delphi.cmu.edu/covidcast/indicator-status/?date=20210330#details

### PR DESCRIPTION
**Pull request by sgratzl**
closes #892

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

encodes the visible status indicator in the URL:

image

### CODE REVIEW

**Comment by krivard** [comment]
Looks like the space in "Symptom Surveys" is causing problems

**Comment by sgratzl** [comment]
> Looks like the space in "Symptom Surveys" is causing problems

fixed

**Comment by krivard** [comment]
thanks, that works for the address bar. Can you propagate that back into the hover url used on the overview?

**Comment by sgratzl** [comment]
> thanks, that works for the address bar. Can you propagate that back into the hover url used on the overview?

done

**Review by krivard — APPROVED** [review]
🎉

**Pull request merged**
