### PR TITLE
Age Groups

### LINKED ISSUE #1138: Age support for age stratification
Our newest Quidel test positivity signals will be broken down by age groups: 0-4, 5-17, 0-17, 18-49, 50-64, 65+.  That is, these will be provided in addition to the original all-ages signal.

I would like the time series plots for Quidel test positivity on the COVIDcast dashboard to allow for viewing the signal broken down by age group.  I'm thinking something simple like this: 

COVIDcast  COVID Antigen Test Positivity Indicator Details

- We add a side toggle called "Age Groups", which defaults to being "off", so the default view is as it is now.  
- There are checkboxes below it that are all disabled (grayed out) and unchecked when the "Age Groups" toggle is off.  
- There is one checkbox for the "All Ages" group and then one checkbox per proper age group.  Each one also shows the color of the corresponding line.  (Colors here are just chosen as a demo; I'm not suggesting we actually use them.)
- When "Age Groups" is toggled "on", then you all these checkboxes are enabled and checked by default.  So you get the "All Ages" signal and every proper age group signal all overlaid, on the time series plot.
- When "Age Groups" is toggled "on", then the "Raw Data" toggle beneath the plot is disabled (no way to display raw data and multiple signals at once, would be too crowded), but the "Show All Dates" toggle is still enabled.  
- Note: while we're at it, I'd like to rename "Show All Dates" to be "All Dates", throughout the dashboard.  That would be consistent with "Raw Data" and "Age Groups" (where we don't start with a verb).  Also, to be clear, the "Include 0 in Y-Axis" toggle will be going away with v3.1, which hasn't been pushed live yet, and I got this screenshot from the live dashboard.

@sgratzl Do you need any other points of clarification and can you give it a shot?

### PR DESCRIPTION
**Pull request by sgratzl**
closes #1138 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

image

similar to the representation of how other regions (neighboring, state, ...) are shown.

### CODE REVIEW

**Comment by ryantibs** [comment]
Thanks for getting started on this! Really cool to finally get to see these signals and play with them on the dashboard.

As per the design itself. Could you try implementing what I mocked up in #1138? The reason I  suggested that (and that I like that idea) is that it separates out the way we show multiple curves across locations (bottom legend) from multiple curves across age groups (right legend).

Also, the way it is now, there is just a lot of space taken up below the plot by the age group legend.

**Comment by krivard** [comment]
I agree with Ryan that we want to visually distinguish between regional and age group stratification, but I also agree with Sam that this should display at the bottom so that we avoid screwing with the margin flow. I know mobile aren't our first priority users but I'd rather not destroy their experience if it's easily avoidable. We're also losing the orderedness by splitting into two columns.

We can stay in the same family of visual styles while highlighting the region-agegroup hierarchy and maintaining orderedness using something like

image

**Comment by sgratzl** [comment]
what about: 

image

**Comment by ryantibs** [comment]
I think it looks great!!

**Comment by sgratzl** [comment]
> I think it looks great!!

is there then anything missing for this PR to be approved?

**Comment by ryantibs** [comment]
I didn't realize you had already implemented it --- I assumed that was just a graphic or screenshot of work in progress.

Thanks Sam. I approved it.

**Review by ryantibs — APPROVED** [review]

**Pull request merged**
