### PR TITLE
chore: rename api param to endpoint

### PR DESCRIPTION
**Pull request by sgratzl**
see https://github.com/cmu-delphi/delphi-epidata/pull/325

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

see also https://github.com/cmu-delphi/delphi-epidata/issues/321

**REQUIRES**: https://github.com/cmu-delphi/delphi-epidata/pull/325 to be merged and deployed

### CODE REVIEW

**Comment by tildechris** [comment]
Ready for review?  cmu-delphi/delphi-epidata#325 looks to be merged.

**Comment by sgratzl** [comment]
> Ready for review? [cmu-delphi/delphi-epidata#325](https://github.com/cmu-delphi/delphi-epidata/pull/325) looks to be merged.

merged yes but I guess not yet deployed.: https://api.covidcast.cmu.edu/epidata/api.php?endpoint=covidcast_meta doesn't work yet.

**Comment by tildechris** [comment]
@krivard, is there an issue that we can watch that will track when https://github.com/cmu-delphi/delphi-epidata/pull/325 gets deployed to production?

**Comment by krivard** [comment]
Epidata automatically deploy to production on merge to main, so you’re good
to go.

**Comment by sgratzl** [comment]
still blocked: https://github.com/cmu-delphi/delphi-epidata/tree/source-to-endpoint isn't merged into main yet

**Comment by krivard** [comment]
Thanks. @benjaminysmith  can you work with @Akvannortwick on the remaining documentation? I'm not sure what the current status is, there might not be a PR yet.

**Comment by benjaminysmith** [comment]
PR from @Akvannortwick is here: https://github.com/cmu-delphi/delphi-epidata/pull/349

**Comment by krivard** [comment]
Merged; should be unblocked now?

**Review by tildechris — APPROVED** [review]
LGTM, if we're able to merge.

**Pull request merged**
