### PR TITLE
New Indicator Status Overview

### PR DESCRIPTION
**Pull request by sgratzl**
**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

current state of the new indicator status overview. 

TODO: 
- [x] needs sheet API meta data for better names
- [x] more descriptive texts

overview:

image

source:
image

image

signal:
image

image

image

### CODE REVIEW

**Comment by sgratzl** [comment]
missing texts:

image

image

image

**Comment by krivard** [comment]
Map says "no data available" for source subdivisions; are we meant to be doing alias dereferencing in the frontend or the API server?
image

**Comment by krivard** [comment]
Contrast too low for "format:fraction" though I suspect that wasn't introduced in this PR
image

**Comment by krivard** [comment]
"Available Signals" table wraps the First Data and Latest Data dates; prefer wrapping Signal or Levels

image

**Comment by krivard** [comment]
Excellent. Can we either float the reference signal to the top of the list, or push the "(reference)" annotation to a separate line, or both? The sea of survey signals makes it difficult to identify.

image

**Comment by sgratzl** [comment]
how about 

image

**Comment by krivard** [comment]
Excellent. Can we tooltip the star with "Reference signal" so it's clear that's what it means

**Comment by sgratzl** [comment]
> Excellent. Can we tooltip the star with "Reference signal" so it's clear that's what it means

sure that was already implemented

**Review by krivard — APPROVED** [review]
👍 

I've released the other pending changes so we're clear to merge this

**Pull request merged**
