### PR TITLE
Fallback to latest in maps

### PR DESCRIPTION
**Pull request by sgratzl**
addresses #1183 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

fallback for the overview + map to the latest available for the levels. Only relevant for the hospital admissions signal, since it has mixed signals on different levels. 

image

image

image

### CODE REVIEW

**Comment by ryantibs** [comment]
@sgratzl --- thank you for turning this around! 

I believe @duanecmu  will provide the review, reading through the original issue to get a sense for what he should look out for (thank you).

I just wanted to flag some small grammar/wording issues: 

- "\* the indicator ..." --> "\* The indicator ..." (capitalization)
- "... available on the geographic level ..." --> "... available at the geographic level ..."
- "The data from ... is shown instead" --> "The data from ... is displayed instead".

**Comment by duanecmu** [comment]
Katie pointed out some issues that need corrected:

1. "* the indicator ..." --> "* The indicator ..." (capitalization)
2. "... available on the geographic level ..." --> "... available at the geographic level ..."
3. "The data from ... is shown instead" --> "The data from ... is displayed instead".

Also need to fix:

1. "*the choropleth map shows no data available... -> "* The chloropleth ..." (capitalization) 
2.

**Comment by duanecmu** [comment]
Yeah, there's a few typos that need to be fixed (see comments for details.)

**Comment by sgratzl** [comment]
> * "* the indicator ..." --> "* The indicator ..." (capitalization)
> 
> * "... available on the geographic level ..." --> "... available at the geographic level ..."
> 
> * "The data from ... is shown instead" --> "The data from ... is displayed instead".

fixed



> 1. "_the choropleth map shows no data available... -> "_ The chloropleth ..." (capitalization)

where do you see that? I cannot find this sentence

**Review by krivard — APPROVED** [review]
👍

**Pull request merged**
