### PR TITLE
Annotation Overview Table

### LINKED ISSUE #879: create "Annotations Overview Page"
**User story**

Review all annotations by time.  Being able to see all annotations gives one a good idea of the challenges of data reporting over time.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #879

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

adds a new page: `/data-anomalies` which shows the plain list of data anomalies similar to the Excel sheet in a nice way:

image

Moreover, I refactored the sort table logic for a simpler reuse

### CODE REVIEW

**Comment by krivard** [comment]
@sgratzl This is good, though I think I want to add a more informative label than Indicator Combination to those cases/deaths entries. Should I do that through a new column in the spreadsheet?

@Letsgohyde I also sense a blurring of intended audience here and am open to ideas on how to resolve. Nontechnical users will definitely care why cases suddenly appeared to increase by 300%, and technical users will care what API queries are affected (so they'll need the exact signal names)... but I don't want to suggest to nontechnical users that understanding the signal names is essential/fundamental to interpreting the data anomaly listed.

**Comment by sgratzl** [comment]
> @sgratzl This is good, though I think I want to add a more informative label than Indicator Combination to those cases/deaths entries. Should I do that through a new column in the spreadsheet?

for the export tab I explicitly split the cases/death signals from the remaining indicator-combination ones, we can do a similar thing here. 

image

**Comment by krivard** [comment]
> explicitly split the cases/death signals

perfect! let's do it

**Comment by sgratzl** [comment]
> @Letsgohyde I also sense a blurring of intended audience here and am open to ideas on how to resolve. Nontechnical users will definitely care why cases suddenly appeared to increase by 300%, and technical users will care what API queries are affected (so they'll need the exact signal names)... but I don't want to suggest to nontechnical users that understanding the signal names is essential/fundamental to interpreting the data anomaly listed.

I assume for non-technical users they will encounter those anomalies just as annotations/warning in the other pages. I thought this page just to be more for data exporters that wanna have an overview.

**Comment by sgratzl** [comment]
as discussed I split the "public health reports" data source in "COVID Cases" and "COVID Deaths"

**Review by chinandrew — APPROVED** [review]
:shipit: :shipit: :shipit:

**Pull request merged**
