### PR TITLE
Reduce layout flicker on Region Details

### LINKED ISSUE #637: Region comparison mode constantly resizes while hovering values
**Actual Behavior:**

When doing a comparison in the "Region" tab, hovering a graph changes the numbers above the graph constantly and creates a very shaky visual

When I...

**Steps to Reproduce the Bug:**

1. go to https://covidcast.cmu.edu/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201113&signalType=value&encoding=color&mode=single&compare=06075&region=41940
2. Hover the COVID Like Symptoms in Community graph from left to right

**Expected behavior**

Graphs and charts would have appropriate sizing to avoid rapid resizing while hovering

**Screenshots**

n/a, it's motion not a static image

**Rating Scale (1 is minor, 7 is severe):**

3 - it makes the comparison mode difficult to use

**Context**

- Browser: Chrome

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by dlaliberte**
closes #637 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

Change layout and formatting to keep legend columns stable as user hovers over various values.
Also fix legend color for first signal to match gray color in chart.

### CODE REVIEW

**Comment by dlaliberte** [comment]
There are a couple edge cases that still need a bit of work.  e.g. With one column, the table expands too much if the window is wide.

**Comment by tildechris** [comment]
Looks like there is still significant flicker:

E3o72DlvNF

I think we need to wait for the next release to take a closer look at this.

**Comment by tildechris** [comment]
Previous screengrab was from the main page, here's one from the region details view:

IGvnwXmXBQ

**Comment by dlaliberte** [comment]
> Looks like there is still significant flicker:

Flickering tooltip is different from flickering layout of the charts and tables.  The tooltip flickers less than it used to, but there are still some more cases when it is drawn off the window that it flickers.

> I think we need to wait for the next release to take a closer look at this.

This change is about the flickering layout.  It's pretty rock solid now.  I wouldn't wait.

**Comment by tildechris** [comment]
Ah, as per our discussion, you fixed the flicker with the chart area, and the tooltip flicker is a different issue.  Let's move forward with the review.

**Review by tildechris — APPROVED** [review]
LGTM.  Thanks Daniel, you can merge.

**Pull request merged**
