### PR TITLE
create staging environment setup

### PR DESCRIPTION
**Pull request by sgratzl**
**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

allows to specify the covidcast endpoint api that should be used during **build time** using an environment variable named `COVIDCAST_ENDPOINT_URL`.  e.g., when setting the env variable on netlfiy, see `netlify.toml` file to use a potential staging server for dev and deployment previews

### CODE REVIEW

**Comment by sgratzl** [comment]
I configured a netlify context `staging` with a corresponding branch called `staging` which will use the staging api server and the additional signal descriptions.  It uses the staging api and https://docs.google.com/document/d/1Yi_ueKvASwyzm6ZJEcrStk5qVIKz94N2yEHlklfnEig/edit# to include additional signals in the app. 

what is missing (which requires more rights than I have) is to define this context in the netlify app

**Comment by krivard** [comment]
Added a staging context to netlify. I'll add the build hook as soon as staging deploys at least once.

Re:whether meta gets merged, that's something we definitely need; at the moment I can't tell experimentally whether we already have it since staging is currently hosting a recent backup of prod.

**Comment by sgratzl** [comment]
I made a dummy change: 

https://staging--cmu-delphi-covidcast.netlify.app/?sensor=fb-survey-smoothed_tested_positive_14d&level=county&date=20201030&signalType=value&encoding=color&mode=overview&region=42003

**Comment by krivard** [comment]
staging-refresh build hook: https://api.netlify.com/build_hooks/5fa1cbd7e95f7000e2a81cd6

**Comment by sgratzl** [comment]
> staging-refresh build hook: https://api.netlify.com/build_hooks/5fa1cbd7e95f7000e2a81cd6

thx I added the link to the google doc. 

so that is missing is merging this PR into dev and then that you guys test it as soon as you have another staging environment

**Review by krivard — APPROVED** [review]
lgtm

**Pull request merged**
