### PR TITLE
mobile table view

### LINKED ISSUE #740: Implement mobile layout for signals table
Design spec in Figma: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=1891%3A35617

In the mock you'll notice a placeholder for the intro summary, this is still being defined. 

Link to the WIP intro section: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=1915%3A33950

### PR DESCRIPTION
**Pull request by sgratzl**
closes #740 

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

current state: 
image

Notes
 * so far I'm using the same color scales as the map
 * the color scale used in the table header is the one of the currently selected sensor
 * a lot of entries are given in percentages, some per 100k, some are just counts. So only cases/deaths fill the per 100k column
 * I manually implemented a weekly aggregation of the values for the heatmap
 * the signal labels are the one from the map / google doc

### CODE REVIEW

**Comment by sgratzl** [comment]
sparkline alternative below:

image

**Comment by Letsgohyde** [comment]
Thanks for putting this together, I think that spark lines are easier to read at a glance, the heat map still has its benefits, but I vote for the spark lines.

**Comment by Letsgohyde** [comment]
When I compare our "Bar visits" Signal the heat map presents the data as if it's fairly mellow, while the sparkline appears much more concerning.
Screen Shot 2021-02-03 at 1 01 41 PM
Screen Shot 2021-02-03 at 1 01 34 PM

@sgratzl maybe we consider displaying a number value rather than a sparkline, but once the user selects the measurement the detailed chart displays. This way we can allow for more space to express the data. Just a thought, what do you think?

**Comment by sgratzl** [comment]
closing in favor of #731 -> see latest comment

**Pull request closed without merging**
